### ISSUE TITLE
Cannot run test

### ISSUE THREAD

**Issue by zixsma** [zixsma/frontend-war-angular#9]
You can see the log here
[https://travis-ci.org/zixsma/frontend-war-angular/builds/238133066](https://travis-ci.org/zixsma/frontend-war-angular/builds/238133066
)

The problem may come from typescript version. Maybe we need to upgrade cli version or fix typescript version to `2.0.10`. Don't know what to do now. It's 6am and I'm so sleepy. I will come back to solve this later if no one fixes it before me.

ref solution:
[https://github.com/angular/angular-cli/issues/5024](https://github.com/angular/angular-cli/issues/5024
)[https://github.com/angular/angular-cli/wiki/stories-rc-update](https://github.com/angular/angular-cli/wiki/stories-rc-update)

**Comment by ronsc** [comment]
I think this problem come from Angular Cli Version 
Because version is diff 1.0.4 and 1.1.0 but typescript is same version 2.0.10

My PR #7 Build on @angular/cli@1.0.4  PASS
See log https://travis-ci.org/zixsma/frontend-war-angular/builds/234078425#L305

And You PR #8 Build on @angular/cli@1.1.0 FAIL
https://travis-ci.org/zixsma/frontend-war-angular/builds/238133307#L276
